// Reads blog_website/content/blog/*.md, parses YAML front-matter, emits
// Postgres INSERT statements (dollar-quoted) for blog_posts + blog_post_tags.
//
// Usage:
//   cd api && dart run tool/import_md.dart > /tmp/blog_inserts.sql
// Then paste the output into migrations/0002_seed.sql.
//
// The script is one-shot — once 0002_seed.sql is committed and applied,
// admin CRUD owns blog content. Delete this script in a follow-up.

import 'dart:io';

import 'package:yaml/yaml.dart';

void main(List<String> args) {
  final repoRoot = _findRepoRoot();
  final dir = Directory('${repoRoot.path}/blog_website/content/blog');
  if (!dir.existsSync()) {
    stderr.writeln('content directory not found: ${dir.path}');
    exit(2);
  }

  final files = dir.listSync().whereType<File>()
      .where((f) => f.path.endsWith('.md')).toList()
    ..sort((a, b) => a.path.compareTo(b.path));

  final buf = StringBuffer()
    ..writeln('-- Auto-generated by api/tool/import_md.dart.')
    ..writeln('-- Source: blog_website/content/blog/*.md')
    ..writeln();

  for (final file in files) {
    final slug = file.uri.pathSegments.last.replaceFirst('.md', '');
    final post = _parse(slug, file.readAsStringSync());
    _emit(buf, post);
  }

  stdout.write(buf.toString());
}

class _Post {
  _Post({
    required this.slug,
    required this.title,
    required this.date,
    required this.tags,
    required this.description,
    required this.body,
  });
  final String slug, title, date, description, body;
  final List<String> tags;
}

_Post _parse(String slug, String raw) {
  const sep = '---\n';
  if (!raw.startsWith(sep)) {
    return _Post(slug: slug, title: slug, date: '', tags: const [], description: '', body: raw.trim());
  }
  final end = raw.indexOf('\n---\n', sep.length);
  if (end == -1) {
    return _Post(slug: slug, title: slug, date: '', tags: const [], description: '', body: raw.trim());
  }
  final fm = loadYaml(raw.substring(sep.length, end)) as YamlMap;
  final body = raw.substring(end + 5).trimLeft();
  return _Post(
    slug: slug,
    title: (fm['title']?.toString() ?? slug),
    date: (fm['date']?.toString() ?? ''),
    tags: ((fm['tags'] as YamlList?)?.map((e) => e.toString()).toList() ?? const []),
    description: (fm['description']?.toString() ?? ''),
    body: body,
  );
}

void _emit(StringBuffer buf, _Post p) {
  if (p.date.isEmpty) {
    stderr.writeln('skipping ${p.slug} — missing date');
    return;
  }
  buf
    ..writeln('-- ${p.slug}')
    ..writeln('WITH ins AS (')
    ..writeln('  INSERT INTO blog_posts')
    ..writeln('    (slug, title, date, description, body_markdown, published)')
    ..writeln('  VALUES (')
    ..writeln('    ${_dq(p.slug)},')
    ..writeln('    ${_dq(p.title)},')
    ..writeln("    DATE '${p.date}',")
    ..writeln('    ${_dq(p.description)},')
    ..writeln('    ${_dq(p.body)},')
    ..writeln('    TRUE')
    ..writeln('  ) RETURNING id')
    ..writeln(')');
  if (p.tags.isEmpty) {
    buf.writeln('SELECT id FROM ins;');
  } else {
    buf.writeln('INSERT INTO blog_post_tags (post_id, tag)');
    final values = p.tags
        .map((t) => '((SELECT id FROM ins), ${_dq(t)})')
        .join(',\n  ');
    buf.writeln('VALUES\n  $values;');
  }
  buf.writeln();
}

/// Dollar-quote a string for safe SQL embedding. Picks a tag that does not
/// occur inside the value.
String _dq(String value) {
  var tag = 'STR';
  while (value.contains('\$$tag\$')) {
    tag += '_';
  }
  return '\$$tag\$$value\$$tag\$';
}

Directory _findRepoRoot() {
  var dir = Directory.current;
  for (var i = 0; i < 6; i++) {
    if (Directory('${dir.path}/blog_website').existsSync() &&
        Directory('${dir.path}/api').existsSync()) {
      return dir;
    }
    if (dir.path == dir.parent.path) break;
    dir = dir.parent;
  }
  throw StateError('could not locate repo root from ${Directory.current.path}');
}
