#!/usr/bin/env bash
# scripts/dev-up.sh — bring up the full dynamic-CMS stack locally for testing.
#
# Idempotent: safe to run multiple times. Generates .env on first run with
# dev-safe defaults. Use scripts/dev-down.sh to stop everything.

set -euo pipefail

cd "$(dirname "$0")/.."
ROOT="$(pwd)"

# ---- ANSI helpers ---------------------------------------------------------
BOLD=$'\033[1m'; DIM=$'\033[2m'; GREEN=$'\033[32m'; YELLOW=$'\033[33m'
BLUE=$'\033[34m'; CYAN=$'\033[36m'; RED=$'\033[31m'; RESET=$'\033[0m'

say()  { printf '%s\n' "$*"; }
ok()   { printf '%s✓%s %s\n' "$GREEN" "$RESET" "$*"; }
warn() { printf '%s!%s %s\n' "$YELLOW" "$RESET" "$*"; }
err()  { printf '%s✗%s %s\n' "$RED" "$RESET" "$*" >&2; }
step() { printf '\n%s== %s ==%s\n' "$BOLD" "$*" "$RESET"; }

# ---- Pre-flight -----------------------------------------------------------
step "Pre-flight"

if ! command -v docker >/dev/null 2>&1; then
  err "docker not found in PATH"; exit 1
fi
if ! docker info >/dev/null 2>&1; then
  err "Docker daemon isn't running. Start Docker Desktop and re-run."; exit 1
fi
ok "Docker daemon reachable"

# The edge network is external to this compose file (in prod it's shared with
# the Caddy stack). Locally we just need it to exist so services can join.
if ! docker network inspect edge >/dev/null 2>&1; then
  docker network create edge >/dev/null
  ok "Created docker network 'edge'"
else
  ok "Network 'edge' already exists"
fi

# ---- .env -----------------------------------------------------------------
step ".env"

DEV_SEED_PASSWORD="devadmin"
if [ ! -f .env ]; then
  cat > .env <<EOF
# Auto-generated by scripts/dev-up.sh on $(date '+%Y-%m-%d %H:%M:%S').
# Safe-for-dev values only — do NOT use these in production.
# Edit GMAIL_APP_PASSWORD with a real App Password if you want to test
# the contact form end-to-end against Gmail SMTP.

DB_PASSWORD=devpw
DATABASE_URL=postgres://portfolio:devpw@postgres:5432/portfolio
JWT_SECRET=dev-jwt-secret-not-for-production-use-please-rotate

GMAIL_USER=consciousmayank@gmail.com
GMAIL_APP_PASSWORD=placeholder-edit-for-real-mail
ADMIN_EMAIL=consciousmayank@gmail.com

SEED_ADMIN_EMAIL=consciousmayank@gmail.com
SEED_ADMIN_PASSWORD=${DEV_SEED_PASSWORD}

CORS_ORIGIN=http://localhost:8090,http://localhost:8091
EOF
  chmod 600 .env
  ok "Wrote .env with dev defaults (seed admin password: ${BOLD}${DEV_SEED_PASSWORD}${RESET})"
else
  ok ".env already present — using as-is"
  if grep -q "^SEED_ADMIN_PASSWORD=" .env; then
    DEV_SEED_PASSWORD="$(grep '^SEED_ADMIN_PASSWORD=' .env | cut -d= -f2-)"
  fi
fi

# ---- Build + boot ---------------------------------------------------------
COMPOSE=(docker compose -f docker-compose.yml -f docker-compose.dev.yml)

step "Building images (first run ~5 min — admin pulls cirruslabs/flutter:stable)"
"${COMPOSE[@]}" build

step "Starting stack"
"${COMPOSE[@]}" up -d --remove-orphans
ok "All containers started"

# ---- Wait for api healthcheck --------------------------------------------
step "Waiting for API to become healthy"
HEALTHY=0
for i in $(seq 1 30); do
  status="$(docker inspect -f '{{.State.Health.Status}}' portfolio-api 2>/dev/null || echo missing)"
  printf '  attempt %2d/30 → %s\n' "$i" "$status"
  if [ "$status" = "healthy" ]; then HEALTHY=1; break; fi
  sleep 2
done

if [ "$HEALTHY" -ne 1 ]; then
  err "API never became healthy. Tail of api logs:"
  "${COMPOSE[@]}" logs api --tail=40 >&2
  exit 1
fi
ok "API healthy"

# ---- Sanity ---------------------------------------------------------------
step "Sanity checks"

posts=$(curl -fsS http://localhost:8080/api/blog | python3 -c 'import json,sys;print(len(json.load(sys.stdin)))' 2>/dev/null || echo "?")
roles=$(curl -fsS http://localhost:8080/api/site | python3 -c 'import json,sys;print(len(json.load(sys.stdin)["roles"]))' 2>/dev/null || echo "?")
ok "GET /api/blog → ${posts} posts"
ok "GET /api/site → ${roles} roles"

# ---- URLs -----------------------------------------------------------------
step "URLs"

printf '  %sPublic site   %s  http://localhost:8090\n' "$BLUE" "$RESET"
printf '  %sAdmin web     %s  http://localhost:8091\n' "$BLUE" "$RESET"
printf '  %sAPI base      %s  http://localhost:8080\n' "$BLUE" "$RESET"
printf '  %sHealth        %s  http://localhost:8080/health\n' "$DIM" "$RESET"
printf '  %sBlog index    %s  http://localhost:8080/api/blog\n' "$DIM" "$RESET"
printf '  %sSite bundle   %s  http://localhost:8080/api/site\n' "$DIM" "$RESET"
printf '  %sPostgres      %s  postgres://portfolio:devpw@localhost:5432/portfolio\n' "$DIM" "$RESET"

# ---- Admin credentials ----------------------------------------------------
step "Admin login"
printf '  Email     %s%s%s\n' "$BOLD" "consciousmayank@gmail.com" "$RESET"
printf '  Password  %s%s%s   %s(seed — rotate via Settings after first login)%s\n' \
       "$BOLD" "$DEV_SEED_PASSWORD" "$RESET" "$DIM" "$RESET"

# ---- Next steps -----------------------------------------------------------
step "Next steps"
cat <<EOF
  ${CYAN}Test the public site:${RESET}
    open http://localhost:8090

  ${CYAN}Log into the admin and try edits:${RESET}
    open http://localhost:8091
    (sign in with the credentials above, then toggle a blog post's published
     flag and reload localhost:8090 — change should appear immediately)

  ${CYAN}Iterate on Flutter admin with hot reload (instead of dockerized):${RESET}
    cd admin && flutter run -d chrome \\
      --dart-define=API_BASE_URL=http://localhost:8080

  ${CYAN}Inspect the database:${RESET}
    docker compose exec postgres psql -U portfolio -d portfolio
    docker compose exec postgres psql -U portfolio -d portfolio \\
      -c 'SELECT slug, published, date FROM blog_posts ORDER BY date DESC;'

  ${CYAN}Tail logs:${RESET}
    docker compose logs -f api web admin-web

  ${CYAN}Test the contact form against real Gmail SMTP:${RESET}
    1. Edit .env → set GMAIL_APP_PASSWORD to a real App Password
    2. docker compose -f docker-compose.yml -f docker-compose.dev.yml up -d api

  ${CYAN}Stop everything:${RESET}
    scripts/dev-down.sh           # stop containers, keep Postgres data
    scripts/dev-down.sh --volumes # nuke Postgres data too (full reset)
EOF

printf '\n%sStack is up.%s\n' "$GREEN$BOLD" "$RESET"
